//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigFamilyWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public string Contacts { get; set; }
        public int SectorId { get; set; }
        public string PriceURL { get; set; }
        public string MinImageUrl { get; set; }
        public string MinTitle { get; set; }
        public string MinKeywords { get; set; }
        public string LampColor { get; set; }
        public string ImageMobileURL { get; set; }
        public string DecorationURL { get; set; }
    }
}
